# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payo_anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaPencere(object):
    def setupUi(self, AnaPencere):
        AnaPencere.setObjectName("AnaPencere")
        AnaPencere.resize(668, 584)
        AnaPencere.setMinimumSize(QtCore.QSize(668, 584))
        AnaPencere.setMaximumSize(QtCore.QSize(668, 584))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        AnaPencere.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Kullanıcılar/H_Cagatay_Sarioglu/Resimler/Uygulama Görselleri/hcs_ikon_16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AnaPencere.setWindowIcon(icon)
        AnaPencere.setStyleSheet("QWidget {\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(240, 240, 240);\n"
"    border-color: rgb(58, 58, 58);\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"    selection-background-color: rgb(255, 153, 0);\n"
"    selection-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"        border-top: 1px solid #000000;\n"
"}\n"
"\n"
"QTableWidget{\n"
"color: #cfcfcf;\n"
"background-color:#363636;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     background-color:rgb(0, 0, 0);\n"
"     border-style: outset;\n"
"    border-width: 1px;\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"  border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-top-width: 0px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 153, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"   color: rgb(255, 255, 255);\n"
"   background-color:rgb(0, 0, 0);\n"
"   border-color:rgb(42, 42, 42);\n"
"   margin-left: 0px;\n"
"   margin-right: 0px;\n"
"   border-bottom-right-radius:4px;\n"
"   border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
"  background-color:rgb(0, 0, 0);\n"
"    border-color:rgb(42, 42, 42);\n"
"    margin-left: 0px;\n"
"      margin-right: 0px;\n"
"    border-bottom-right-radius:4px;\n"
"    border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"   margin-bottom: 4px;\n"
"   border-bottom-right-radius:4px;\n"
"   border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(101, 101, 101);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(0, 200, 0, 255), stop:1 rgba(30, 230, 30, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background:rgb(0, 0, 0);\n"
"    color: rgb(255, 153, 0);\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"      spacing: 3px; \n"
"    padding: 1px 4px;\n"
"      background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected { \n"
"      background:rgb(115, 115, 115);\n"
"}\n"
"\n"
"QMenu {\n"
"    border-width: 2px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 153, 0);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; \n"
"    padding: 3px 15px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    spacing: 3px; \n"
"    padding: 3px 15px;\n"
"    background:rgb(115, 115, 115);\n"
"    color:rgb(255, 255, 255);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(AnaPencere)
        self.centralwidget.setObjectName("centralwidget")
        self.grpKullaniciGiris = QtWidgets.QGroupBox(self.centralwidget)
        self.grpKullaniciGiris.setGeometry(QtCore.QRect(30, 30, 481, 191))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.grpKullaniciGiris.setFont(font)
        self.grpKullaniciGiris.setObjectName("grpKullaniciGiris")
        self.layoutWidget = QtWidgets.QWidget(self.grpKullaniciGiris)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 451, 139))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblUygulama = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblUygulama.setFont(font)
        self.lblUygulama.setObjectName("lblUygulama")
        self.horizontalLayout_4.addWidget(self.lblUygulama)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lneUygulama = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneUygulama.setMinimumSize(QtCore.QSize(300, 0))
        self.lneUygulama.setObjectName("lneUygulama")
        self.horizontalLayout_4.addWidget(self.lneUygulama)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblKullanici = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblKullanici.setFont(font)
        self.lblKullanici.setObjectName("lblKullanici")
        self.horizontalLayout_3.addWidget(self.lblKullanici)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lneKullanici = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneKullanici.setMinimumSize(QtCore.QSize(300, 0))
        self.lneKullanici.setObjectName("lneKullanici")
        self.horizontalLayout_3.addWidget(self.lneKullanici)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblAcarga = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblAcarga.setFont(font)
        self.lblAcarga.setObjectName("lblAcarga")
        self.horizontalLayout_2.addWidget(self.lblAcarga)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lneAcarga = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneAcarga.setMinimumSize(QtCore.QSize(300, 0))
        self.lneAcarga.setObjectName("lneAcarga")
        self.horizontalLayout_2.addWidget(self.lneAcarga)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblEkBilgi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblEkBilgi.setFont(font)
        self.lblEkBilgi.setObjectName("lblEkBilgi")
        self.horizontalLayout.addWidget(self.lblEkBilgi)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lneEkBilgi = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneEkBilgi.setMinimumSize(QtCore.QSize(300, 0))
        self.lneEkBilgi.setObjectName("lneEkBilgi")
        self.horizontalLayout.addWidget(self.lneEkBilgi)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.dgmTumu = QtWidgets.QPushButton(self.centralwidget)
        self.dgmTumu.setGeometry(QtCore.QRect(30, 480, 121, 50))
        self.dgmTumu.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dgmTumu.setFont(font)
        self.dgmTumu.setObjectName("dgmTumu")
        self.dgmCik = QtWidgets.QPushButton(self.centralwidget)
        self.dgmCik.setGeometry(QtCore.QRect(570, 480, 61, 50))
        self.dgmCik.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dgmCik.setFont(font)
        self.dgmCik.setObjectName("dgmCik")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(530, 30, 98, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dgmSakla = QtWidgets.QPushButton(self.layoutWidget1)
        self.dgmSakla.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dgmSakla.setFont(font)
        self.dgmSakla.setObjectName("dgmSakla")
        self.verticalLayout_2.addWidget(self.dgmSakla)
        self.dgmGuncelle = QtWidgets.QPushButton(self.layoutWidget1)
        self.dgmGuncelle.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dgmGuncelle.setFont(font)
        self.dgmGuncelle.setObjectName("dgmGuncelle")
        self.verticalLayout_2.addWidget(self.dgmGuncelle)
        self.dgmSil = QtWidgets.QPushButton(self.layoutWidget1)
        self.dgmSil.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dgmSil.setFont(font)
        self.dgmSil.setObjectName("dgmSil")
        self.verticalLayout_2.addWidget(self.dgmSil)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(112, 240, 401, 42))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lneAra = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lneAra.setMinimumSize(QtCore.QSize(250, 30))
        self.lneAra.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lneAra.setObjectName("lneAra")
        self.horizontalLayout_5.addWidget(self.lneAra)
        spacerItem4 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.dgmAra = QtWidgets.QPushButton(self.layoutWidget2)
        self.dgmAra.setMinimumSize(QtCore.QSize(50, 30))
        self.dgmAra.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dgmAra.setFont(font)
        self.dgmAra.setObjectName("dgmAra")
        self.horizontalLayout_5.addWidget(self.dgmAra)
        self.dgmTemizle = QtWidgets.QPushButton(self.layoutWidget2)
        self.dgmTemizle.setMinimumSize(QtCore.QSize(50, 30))
        self.dgmTemizle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dgmTemizle.setFont(font)
        self.dgmTemizle.setObjectName("dgmTemizle")
        self.horizontalLayout_5.addWidget(self.dgmTemizle)
        self.anaSayfaTablosu = QtWidgets.QTableWidget(self.centralwidget)
        self.anaSayfaTablosu.setGeometry(QtCore.QRect(30, 300, 601, 161))
        self.anaSayfaTablosu.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.anaSayfaTablosu.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.anaSayfaTablosu.setShowGrid(False)
        self.anaSayfaTablosu.setWordWrap(False)
        self.anaSayfaTablosu.setCornerButtonEnabled(True)
        self.anaSayfaTablosu.setRowCount(100)
        self.anaSayfaTablosu.setColumnCount(5)
        self.anaSayfaTablosu.setObjectName("anaSayfaTablosu")
        self.anaSayfaTablosu.horizontalHeader().setCascadingSectionResizes(False)
        self.anaSayfaTablosu.horizontalHeader().setHighlightSections(True)
        self.anaSayfaTablosu.horizontalHeader().setMinimumSectionSize(40)
        self.anaSayfaTablosu.horizontalHeader().setSortIndicatorShown(False)
        self.anaSayfaTablosu.horizontalHeader().setStretchLastSection(False)
        self.anaSayfaTablosu.verticalHeader().setVisible(False)
        AnaPencere.setCentralWidget(self.centralwidget)
        self.menuCubugu = QtWidgets.QMenuBar(AnaPencere)
        self.menuCubugu.setGeometry(QtCore.QRect(0, 0, 668, 23))
        self.menuCubugu.setObjectName("menuCubugu")
        self.menuYardim = QtWidgets.QMenu(self.menuCubugu)
        self.menuYardim.setObjectName("menuYardim")
        self.menuHakkinda = QtWidgets.QMenu(self.menuYardim)
        self.menuHakkinda.setObjectName("menuHakkinda")
        AnaPencere.setMenuBar(self.menuCubugu)
        self.durumCubugu = QtWidgets.QStatusBar(AnaPencere)
        self.durumCubugu.setObjectName("durumCubugu")
        AnaPencere.setStatusBar(self.durumCubugu)
        self.actHcsYazilim = QtWidgets.QAction(AnaPencere)
        self.actHcsYazilim.setObjectName("actHcsYazilim")
        self.menuHakkinda.addAction(self.actHcsYazilim)
        self.menuYardim.addAction(self.menuHakkinda.menuAction())
        self.menuCubugu.addAction(self.menuYardim.menuAction())

        self.retranslateUi(AnaPencere)
        QtCore.QMetaObject.connectSlotsByName(AnaPencere)

    def retranslateUi(self, AnaPencere):
        _translate = QtCore.QCoreApplication.translate
        AnaPencere.setWindowTitle(_translate("AnaPencere", "Parola Yöneticisi"))
        self.grpKullaniciGiris.setTitle(_translate("AnaPencere", "Kullanıcı Giriş Bilgileri"))
        self.lblUygulama.setText(_translate("AnaPencere", "Uygulama:"))
        self.lneUygulama.setPlaceholderText(_translate("AnaPencere", "Kullandığınız uygulamanın adı"))
        self.lblKullanici.setText(_translate("AnaPencere", "Kullanıcı:"))
        self.lneKullanici.setPlaceholderText(_translate("AnaPencere", "Kullanıcı adınız veya e-postanız"))
        self.lblAcarga.setText(_translate("AnaPencere", "Açarga:"))
        self.lneAcarga.setPlaceholderText(_translate("AnaPencere", "Belirlediğiniz parolanız"))
        self.lblEkBilgi.setText(_translate("AnaPencere", "Ek Bilgi:"))
        self.lneEkBilgi.setPlaceholderText(_translate("AnaPencere", "Varsa ek bilgileriniz"))
        self.dgmTumu.setText(_translate("AnaPencere", "Tümünü Göster"))
        self.dgmCik.setText(_translate("AnaPencere", "Çık"))
        self.dgmSakla.setText(_translate("AnaPencere", "Sakla"))
        self.dgmGuncelle.setText(_translate("AnaPencere", "Güncelle"))
        self.dgmSil.setText(_translate("AnaPencere", "Sil"))
        self.lneAra.setPlaceholderText(_translate("AnaPencere", "Aratacağınız anahtar sözcük"))
        self.dgmAra.setText(_translate("AnaPencere", "Ara"))
        self.dgmTemizle.setText(_translate("AnaPencere", "Temizle"))
        self.menuYardim.setTitle(_translate("AnaPencere", "Yardım"))
        self.menuHakkinda.setTitle(_translate("AnaPencere", "Hakkında"))
        self.actHcsYazilim.setText(_translate("AnaPencere", "hçsYazılım"))
