# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payo_tablo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BilgilerTablosu(object):
    def setupUi(self, BilgilerTablosu):
        BilgilerTablosu.setObjectName("BilgilerTablosu")
        BilgilerTablosu.resize(933, 658)
        BilgilerTablosu.setMinimumSize(QtCore.QSize(933, 658))
        BilgilerTablosu.setMaximumSize(QtCore.QSize(933, 658))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Kullanıcılar/H_Cagatay_Sarioglu/Resimler/Uygulama Görselleri/hcs_ikon_16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BilgilerTablosu.setWindowIcon(icon)
        BilgilerTablosu.setStyleSheet("QWidget {\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(240, 240, 240);\n"
"    border-color: rgb(58, 58, 58);\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"    selection-background-color: rgb(255, 153, 0);\n"
"    selection-color: rgb(0, 0, 0);\n"
"}\n"
"QTableWidget{\n"
"color: #cfcfcf;\n"
"background-color:#363636;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"        border-top: 1px solid #000000;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     background-color:rgb(0, 0, 0);\n"
"     border-style: outset;\n"
"    border-width: 1px;\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"  border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-top-width: 0px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 153, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"   color: rgb(255, 255, 255);\n"
"   background-color:rgb(0, 0, 0);\n"
"   border-color:rgb(42, 42, 42);\n"
"   margin-left: 0px;\n"
"   margin-right: 0px;\n"
"   border-bottom-right-radius:4px;\n"
"   border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
"  background-color:rgb(0, 0, 0);\n"
"    border-color:rgb(42, 42, 42);\n"
"    margin-left: 0px;\n"
"      margin-right: 0px;\n"
"    border-bottom-right-radius:4px;\n"
"    border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"   margin-bottom: 4px;\n"
"   border-bottom-right-radius:4px;\n"
"   border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(101, 101, 101);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(0, 200, 0, 255), stop:1 rgba(30, 230, 30, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background:rgb(0, 0, 0);\n"
"    color: rgb(255, 153, 0);\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"      spacing: 3px; \n"
"    padding: 1px 4px;\n"
"      background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected { \n"
"      background:rgb(115, 115, 115);\n"
"}\n"
"\n"
"QMenu {\n"
"    border-width: 2px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 153, 0);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; \n"
"    padding: 3px 15px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    spacing: 3px; \n"
"    padding: 3px 15px;\n"
"    background:rgb(115, 115, 115);\n"
"    color:rgb(255, 255, 255);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"}")
        self.tblKayitlar = QtWidgets.QTableWidget(BilgilerTablosu)
        self.tblKayitlar.setGeometry(QtCore.QRect(20, 20, 891, 551))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        self.tblKayitlar.setFont(font)
        self.tblKayitlar.setStyleSheet("")
        self.tblKayitlar.setFrameShape(QtWidgets.QFrame.Panel)
        self.tblKayitlar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tblKayitlar.setRowCount(100)
        self.tblKayitlar.setColumnCount(5)
        self.tblKayitlar.setObjectName("tblKayitlar")
        self.dgmKapat = QtWidgets.QPushButton(BilgilerTablosu)
        self.dgmKapat.setGeometry(QtCore.QRect(810, 590, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        self.dgmKapat.setFont(font)
        self.dgmKapat.setObjectName("dgmKapat")
        self.layoutWidget = QtWidgets.QWidget(BilgilerTablosu)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 590, 183, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblKayitBildirgec = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lblKayitBildirgec.setFont(font)
        self.lblKayitBildirgec.setObjectName("lblKayitBildirgec")
        self.horizontalLayout.addWidget(self.lblKayitBildirgec)
        self.lblKayitGosterim = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lblKayitGosterim.setFont(font)
        self.lblKayitGosterim.setText("")
        self.lblKayitGosterim.setObjectName("lblKayitGosterim")
        self.horizontalLayout.addWidget(self.lblKayitGosterim)

        self.retranslateUi(BilgilerTablosu)
        QtCore.QMetaObject.connectSlotsByName(BilgilerTablosu)

    def retranslateUi(self, BilgilerTablosu):
        _translate = QtCore.QCoreApplication.translate
        BilgilerTablosu.setWindowTitle(_translate("BilgilerTablosu", "Bilgiler Tablosu"))
        self.dgmKapat.setText(_translate("BilgilerTablosu", "Kapat"))
        self.lblKayitBildirgec.setText(_translate("BilgilerTablosu", "Toplam Kayıt:"))
