# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payo_giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GirisSayfasi(object):
    def setupUi(self, GirisSayfasi):
        GirisSayfasi.setObjectName("GirisSayfasi")
        GirisSayfasi.resize(446, 290)
        GirisSayfasi.setMinimumSize(QtCore.QSize(446, 290))
        GirisSayfasi.setMaximumSize(QtCore.QSize(446, 290))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Kullanıcılar/H_Cagatay_Sarioglu/Resimler/Uygulama Görselleri/hcs_ikon_16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GirisSayfasi.setWindowIcon(icon)
        GirisSayfasi.setStyleSheet("QWidget {\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(240, 240, 240);\n"
"    border-color: rgb(58, 58, 58);\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"    selection-background-color: rgb(255, 153, 0);\n"
"    selection-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"        border-top: 1px solid #000000;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     background-color:rgb(0, 0, 0);\n"
"     border-style: outset;\n"
"    border-width: 1px;\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"  border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-top-width: 0px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 153, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"   color: rgb(255, 255, 255);\n"
"   background-color:rgb(0, 0, 0);\n"
"   border-color:rgb(42, 42, 42);\n"
"   margin-left: 0px;\n"
"   margin-right: 0px;\n"
"   border-bottom-right-radius:4px;\n"
"   border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
"  background-color:rgb(0, 0, 0);\n"
"    border-color:rgb(42, 42, 42);\n"
"    margin-left: 0px;\n"
"      margin-right: 0px;\n"
"    border-bottom-right-radius:4px;\n"
"    border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"   margin-bottom: 4px;\n"
"   border-bottom-right-radius:4px;\n"
"   border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(101, 101, 101);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(0, 200, 0, 255), stop:1 rgba(30, 230, 30, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background:rgb(0, 0, 0);\n"
"    color: rgb(255, 153, 0);\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"      spacing: 3px; \n"
"    padding: 1px 4px;\n"
"      background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected { \n"
"      background:rgb(115, 115, 115);\n"
"}\n"
"\n"
"QMenu {\n"
"    border-width: 2px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 153, 0);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; \n"
"    padding: 3px 15px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    spacing: 3px; \n"
"    padding: 3px 15px;\n"
"    background:rgb(115, 115, 115);\n"
"    color:rgb(255, 255, 255);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"}")
        self.lblBilgilendirme = QtWidgets.QLabel(GirisSayfasi)
        self.lblBilgilendirme.setGeometry(QtCore.QRect(154, 260, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        self.lblBilgilendirme.setFont(font)
        self.lblBilgilendirme.setText("")
        self.lblBilgilendirme.setObjectName("lblBilgilendirme")
        self.lblGirisBasligi = QtWidgets.QLabel(GirisSayfasi)
        self.lblGirisBasligi.setGeometry(QtCore.QRect(130, 20, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lblGirisBasligi.setFont(font)
        self.lblGirisBasligi.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGirisBasligi.setObjectName("lblGirisBasligi")
        self.layoutWidget = QtWidgets.QWidget(GirisSayfasi)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 70, 301, 137))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblKullaniciAdi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lblKullaniciAdi.setFont(font)
        self.lblKullaniciAdi.setObjectName("lblKullaniciAdi")
        self.horizontalLayout.addWidget(self.lblKullaniciAdi)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lneKullaniciAdi = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneKullaniciAdi.setMinimumSize(QtCore.QSize(170, 0))
        self.lneKullaniciAdi.setObjectName("lneKullaniciAdi")
        self.horizontalLayout.addWidget(self.lneKullaniciAdi)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblParola = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.lblParola.setFont(font)
        self.lblParola.setObjectName("lblParola")
        self.horizontalLayout_2.addWidget(self.lblParola)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lneParola = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneParola.setMinimumSize(QtCore.QSize(170, 0))
        self.lneParola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneParola.setObjectName("lneParola")
        self.horizontalLayout_2.addWidget(self.lneParola)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.dgmGirisYap = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        self.dgmGirisYap.setFont(font)
        self.dgmGirisYap.setObjectName("dgmGirisYap")
        self.verticalLayout.addWidget(self.dgmGirisYap)
        self.dgmHesapAc = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        self.dgmHesapAc.setFont(font)
        self.dgmHesapAc.setObjectName("dgmHesapAc")
        self.verticalLayout.addWidget(self.dgmHesapAc)

        self.retranslateUi(GirisSayfasi)
        QtCore.QMetaObject.connectSlotsByName(GirisSayfasi)

    def retranslateUi(self, GirisSayfasi):
        _translate = QtCore.QCoreApplication.translate
        GirisSayfasi.setWindowTitle(_translate("GirisSayfasi", "Parola Yöneticisi"))
        self.lblGirisBasligi.setText(_translate("GirisSayfasi", "~ GİRİŞ ~"))
        self.lblKullaniciAdi.setText(_translate("GirisSayfasi", "Kullanıcı adı:"))
        self.lblParola.setText(_translate("GirisSayfasi", "Parola:"))
        self.dgmGirisYap.setText(_translate("GirisSayfasi", "Giriş Yap"))
        self.dgmHesapAc.setText(_translate("GirisSayfasi", "Hesap Aç"))
